# These are supported funding model platforms

github: [silver-blue-space]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/@wcj/github-rank
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
custom: https://silver-blue-space.github.io/sponsor.html
