name: Build and Deploy Github Trending
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '30 0,12 * * *'
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/

    - run: npm ci

    - run: npm run get:trending

    - run: npm run get:hf-trending

    - run: npm run get:hf-papers

    - run: npm run get:openai-news

    - run: npm run get:anthropic-news

    - run: npm run get:qbitai

    - run: npm run start

    - name: Build and Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./web
